# local
# web相关的配置参数
server:
  port: 9000
  compression:
    enabled=true: true
    min-response-size: 1024
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

# mybatis相关的参数
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  table:
    auto : none
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml

# 日志相关配置参数
logging:
  level:
    com.shenju.protocol.logimpl.mapper : debug

# spring相关配置参数
spring:
  mvc: 
    static-path-pattern: /**
  resources:
    static-locations: classpath:/pages/
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  datasource:
    hikari:
      minimum-idle: 60
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 60000
      validation-timeout: 3000
      pool-name: DatebookHikariCP
      max-lifetime: 60000
      login-timeout: 5
      connection-timeout: 60000
      connection-test-query: SELECT 1

    dynamic:
      primary: test #设置默认的数据源或者数据源组,默认值即为master
      datasource:
        ota:
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useLegacyDatetimeCode=false&serverTimezone=UTC

# 用户自定义的参数
access-token:
  service-secret: test0001
swagger-url: 127.0.0.1:9000

# aiyun相关的参数
aliyun:
  oss:
    access-key-id: 123
    access-key-secret: 123
    bucket: test-test
    endpoint: oss-cn-beijing.aliyuncs.com
    dir: local
    